=== cicidi/cicidi-home/src/main/resources/resume_config/profile.dtd
<!ELEMENT profile (firstName,lastName,contact,educationList,workExperienceList)*>

        <!ELEMENT firstName (#PCDATA)>
        <!ELEMENT lastName (#PCDATA)>
        <!ELEMENT faceImg (#PCDATA )>

        <!ELEMENT objective (title, personalEstimate, interests, whyCreateThisPage,contentImg)>
        <!ATTLIST objective type CDATA #IMPLIED>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT personalEstimate (#PCDATA)>
                <!ELEMENT interests (#PCDATA)>
                <!ELEMENT whyCreateThisPage (#PCDATA)>
                <!ELEMENT contentImg (#PCDATA)>

        <!ELEMENT contact (phone,email, address, linkList)>
        <!ATTLIST contact type CDATA #IMPLIED>
                <!ELEMENT phone (#PCDATA)>
                <!ELEMENT email (#PCDATA)>
                <!ELEMENT address (number, street, city, state,country,zipCode)>
                <!ATTLIST address type CDATA #IMPLIED>
                        <!ELEMENT number (#PCDATA)>
                        <!ELEMENT street (#PCDATA)>
                        <!ELEMENT city (#PCDATA)>
                        <!ELEMENT state (#PCDATA)>
                        <!ELEMENT country (#PCDATA)>
                        <!ELEMENT zipCode (#PCDATA)>
                        <!ELEMENT linkList (link)>
                        <!ATTLIST linkList type CDATA #IMPLIED>
                        <!ELEMENT link (name,url,pic)>
                                <!ELEMENT url (#PCDATA)>
                                <!ELEMENT pic (#PCDATA)>
        <!ELEMENT educationList (education)>
        <!ATTLIST educationList type CDATA #IMPLIED>
                <!ELEMENT education (name,address,start,end,startName,endName,length,photo,icon,major,degree)>
                <!ELEMENT name (#PCDATA)>
                <!ELEMENT start (#PCDATA)>
                <!ELEMENT end (#PCDATA)>
                <!ELEMENT startName (#PCDATA)>
                <!ELEMENT endName (#PCDATA)>
                <!ELEMENT length (#PCDATA)>
                <!ELEMENT photo (#PCDATA)>
                <!ELEMENT icon (#PCDATA)>
                <!ELEMENT major (#PCDATA)>
                <!ELEMENT degree (#PCDATA)>
        <!ELEMENT workExperienceList (workExperience)>
        <!ATTLIST workExperience type CDATA #IMPLIED>
                <!ELEMENT workExperience (name,address,start,end,startName,endName,length,photo,icon,summary,role,bulletList)>
                <!ELEMENT summary (#PCDATA)>
                <!ELEMENT role (#PCDATA)>
                <!ELEMENT bulletList (bullet)>
                <!ATTLIST bulletList type CDATA #IMPLIED>
                        <!ELEMENT bullet (content,bulletList)>
                            <!ELEMENT content (#PCDATA)>
        <!ELEMENT skillSets (category)>
        <!ATTLIST category type CDATA #IMPLIED>
                <!ELEMENT category (name,list,technologyList)>
                        <!ELEMENT list (#PCDATA)>
                        <!ELEMENT technologyList (technology)>
                                <!ELEMENT technology (#PCDATA)>

=== cicidi/cicidi-home/src/main/resources/resume_config/resume_copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile>
    <firstName>Walter</firstName>
    <lastName>Chen</lastName>
    <faceImg>
        https://lh3.googleusercontent.com/6d2fKSmeysdXe-9oGf1vNgBXcleP-Y3xmJGjF5CYQ2dFs0X2PkDuzplkezE9ccKZuG3GN75tNuIqRSAUtCs1NfSktNXc5yD9w1Ry7rwIGLFh5YAtShEtrtljX3vRUIbVDOf60Oj4_Bgi4-j7zjDXKTnHvSEOwk1ssS245BeJvVBLV3r9E99Z7YDJvoXNnxTrZ1Sa1Ir65i-E5REO5iu-LzPNwGENIPyfdZEXcqeD2HH1-qze3QplwCuA-Vc7e9t6zUbO4cWS7xL9ioLjEGOmnmX6IVMpNsvtc_SzrHMfb-ETJa5iV5j4MKLv0wLiCDWGUFd2YuOHHFOym6qV0_UzyCnFYxz7idA-Ltbc6ThBP1Lwt7gDE7GklazLgcFc5U1Lpb8zmhSycI6AIMhPrH-7cpsUFbs-4uLCkR67bcvSzLNXF_aauhpUivu6oC98DadoJDwmvzGc9f2VQz9zZLoY_3rdCnbapGiOm5Zs-WAVLmv_XRhNmDqdu6PxhopqQRsFYWJeOj6oCMwIxGgOYsqb7WJs-nJ59L8vHHGn9DPqhXrvnTeLvizu4wvJZUSBUNljFk_X05u2Wjf4577Rsb6NZYsTjLnlsWVxL6oeGCLQ2p76s25rM_R3=s935-no
    </faceImg>
    <objective>
        <title></title>
        <personalEstimate>7 yrs Java Experience, Full stack developer</personalEstimate>
        <interests>I am interest in any kind of new technolgoy</interests>
        <whyCreateThisPage></whyCreateThisPage>
        <illustrator></illustrator>
    </objective>
    <contact type="contact">
        <phone></phone>
        <address type="address">
            <number></number>
            <street></street>
            <city>Fremont</city>
            <state>CA</state>
            <country></country>
            <zipCode></zipCode>
        </address>
        <email>cicidi@gmail.com</email>
        <website>www.ganshaa.com</website>
        <github>cicidi.github.com</github>
        <linkedin>myLinkedInAccount</linkedin>
    </contact>
    <educationList type="education">
        <education>
            <name>University of Florida</name>
            <address type="">
                <number></number>
                <street></street>
                <city>Gainesville</city>
                <state>Florida</state>
                <country>US</country>
                <zipCode></zipCode>
            </address>
            <start>August 2010</start>
            <end>April 2012</end>
            <length>1yrs 8mos</length>
            <photo></photo>
            <icon>https://media.licdn.com/mpr/mpr/shrink_200_200/p/1/005/008/0b8/03e2d71.png</icon>
            <major>Information Systems and Operations Management</major>
            <degree>Master</degree>
        </education>
        <education>
            <name>Dalian Maritime University</name>
            <address type="">
                <number></number>
                <street></street>
                <city>Da Lian</city>
                <state>Liao Ning</state>
                <country>China</country>
                <zipCode></zipCode>
            </address>
            <start>September 2004</start>
            <end>June 2008</end>
            <length>3yrs 9mos</length>
            <photo></photo>
            <icon>https://upload.wikimedia.org/wikipedia/en/3/3a/Dalian_Maritime_University_logo.png</icon>
            <major>Business</major>
            <degree>Bachelor</degree>
        </education>
    </educationList>
    <workExperienceList>
        <workExperience type="workExperience">
            <name>Blackhawk network</name>
            <address type="address">
                <number></number>
                <street></street>
                <city>Pleasanton</city>
                <state>CA</state>
                <country>US</country>
                <zipCode></zipCode>
            </address>
            <start>October 2015</start>
            <end>Present</end>
            <length>1yrs 4mos</length>
            <photo></photo>
            <icon>https://pbs.twimg.com/profile_images/438113203432595456/rBS9OH2u_400x400.png</icon>
            <summary>I am good</summary>
            <role>Senior developer</role>
            <bulletList>
                <bullet>
                    <content>task1</content>
                </bullet>
                <bullet>
                    <content>task2</content>
                </bullet>
            </bulletList>
        </workExperience>
        <workExperience type="workExperience">
            <name>Apple</name>
            <address type="address">
                <number></number>
                <street></street>
                <city>Sunnyvale</city>
                <state>CA</state>
                <country>US</country>
                <zipCode></zipCode>
            </address>
            <start>April 2015</start>
            <end>October 2015</end>
            <length>6 month</length>
            <photo></photo>
            <icon>
                https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png?201701231950
            </icon>
            <summary>I like macbook</summary>
            <role>Senior developer Apple</role>
            <bulletList>
                <bullet>
                    <content>task1</content>
                </bullet>
                <bullet>
                    <content>task2</content>
                </bullet>
            </bulletList>
        </workExperience>
        <workExperience type="workExperience">
            <name>Huawei</name>
            <address type="address">
                <number></number>
                <street></street>
                <city>Santa Clara</city>
                <state>CA</state>
                <country>US</country>
                <zipCode></zipCode>
            </address>
            <start>May 2014</start>
            <end>April 2015</end>
            <length>11 month</length>
            <photo></photo>
            <icon>https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Huawei.svg/150px-Huawei.svg.png</icon>
            <summary>I like macbook</summary>
            <role>Java developer</role>
            <bulletList>
                <bullet>
                    <content>task1</content>
                </bullet>
                <bullet>
                    <content>task2</content>
                </bullet>
            </bulletList>
        </workExperience>
        <workExperience type="workExperience">
            <name>CGI</name>
            <address type="address">
                <number></number>
                <street></street>
                <city>Belton</city>
                <state>TX</state>
                <country>US</country>
                <zipCode></zipCode>
            </address>
            <start>May 2013</start>
            <end>May 2014</end>
            <length>12 month</length>
            <photo></photo>
            <icon>https://www.cgi.com/sites/default/files/cgi-logo-430.png</icon>
            <summary>I like macbook</summary>
            <role>Java Developer</role>
            <bulletList>
                <bullet>
                    <content>task1</content>
                </bullet>
                <bullet>
                    <content>task2</content>
                </bullet>
            </bulletList>
        </workExperience>
    </workExperienceList>
    <skillSet>
        <category type="">
            <name>Spring</name>
            <technologyList>
                <technology>Spring MVC</technology>
                <technology>Spring Boot</technology>
                <technology>Spring Data</technology>
            </technologyList>
        </category>
        <category type="">
            <name>Big Data</name>
            <technologyList>
                <technology>Hadoop</technology>
            </technologyList>
        </category>
    </skillSet>

</profile>
