=== cicidi/cicidi-home/src/main/resources/resume_sample_code/resume.dtd
<!ELEMENT resume (school,job)*>

        <!ELEMENT school (name, degree, year, location)>
        <!ATTLIST school type CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT degree (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT location (city, state)>
        <!ELEMENT state (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT job (name, degree, year, location)>
        <!ATTLIST job type CDATA #REQUIRED>

=== cicidi/cicidi-home/src/main/resources/resume_sample_code/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resume SYSTEM "resume.dtd">
<resume>
    <!-- complete content goes here -->
    <school type="college">
        <name>Austin Community College</name>
        <degree>Associates of Applied Science</degree>
        <year>2013</year>
        <location>
            <city>Austin</city>
            <state>Texas</state>
        </location>
    </school>
    <job type="">
        <name></name>
        <degree></degree>
        <year></year>
        <location>
            <city></city>
            <state></state>
        </location>
    </job>
</resume>
